[custom.wezterm_connect]
description = "Display wezterm connection status"
command = 'echo "$USER in ⛵ $HOST"'
when = '[[ "$WEZTERM_EXECUTABLE" =~ "wezterm-mux-server" ]]'
format = "[$output]($style) "
style = "bold blue"

[custom.proxy]
description = "Display proxy status"
symbol = "🚀 "
when = '[ -n "$http_proxy" ]'
format = "[$symbol]($style) "
style = "bold yellow"
