[custom.wezterm_status]
description = "Display wezterm connection status"
command = "echo $HOST"
symbol = "⛵ "
when = '[[ "$WEZTERM_EXECUTABLE" =~ "wezterm-mux-server" ]]'
format = "[$symbol$output]($style) "
style = "bold blue"

[custom.proxy]
description = "Display proxy status"
symbol = "🚀 "
when = '[ -n "$http_proxy" ]'
format = "[$symbol]($style) "
style = "bold yellow"
